### ISSUE TITLE
Module issue

### ISSUE THREAD

**Issue by mondiedmond** [opengento/magento2-country-switcher#1]
HI! I have an issue with the module.. After country is selected,  <span data-bind="text: countrySwitcher().name"></span> doesn't show the selected country, it returns to Select Country

**Comment by thomas-kl1** [comment]
Hi @mondiedmond could you give me further details about your environment? So I can try to reproduce the issue?
What's your Magento version? Have you any error in the developer console of the navigator you are using?

**Comment by thomas-kl1** [comment]
Hi, thank you! It has been fixed in commit d81d6e79318251d40c0c16944b6c7791037a6d65 and is part of the release 1.0.3

**Comment by thomas-kl1** [comment]
@mondiedmond feel free to star the module if you enjoy it :)

**Comment by mondiedmond** [comment]
Thank you! This commit has resolved my issue. Now I need to insert the country switcher into my theme phtml template file because the module shows up only in Magento Luma theme.

**Comment by thomas-kl1** [comment]
You can use the following:

If you want the popin one, use this template: `Opengento_CountrySwitcher::switch/popin/forehead.phtml`

If you want the field list, use this template: `Opengento_CountrySwitcher::switch/country/forehead.phtml`

Desktop view:
```xml
        <block name="country_switcher" template="Opengento_CountrySwitcher::switch/popin/forehead.phtml">
            <arguments>
                <argument name="localized" xsi:type="object">Opengento\CountrySwitcher\ViewModel\Localized</argument>
                <argument name="switcherProvider" xsi:type="object">Opengento\CountrySwitcher\ViewModel\SwitcherUrlProvider</argument>
                <argument name="countryViewModel" xsi:type="object">Opengento\CountrySwitcher\ViewModel\SwitchCountry\Forehead</argument>
                <argument name="urlAction" xsi:type="url" path="stores/country/redirect"/>
            </arguments>
            <block class="Magento\Framework\View\Element\Template" name="store_language_more" as="more" template="Opengento_CountrySwitcher::switch/country/more.phtml">
                <arguments>
                    <argument name="localized" xsi:type="object">Opengento\CountrySwitcher\ViewModel\Localized</argument>
                    <argument name="switcherProvider" xsi:type="object">Opengento\CountrySwitcher\ViewModel\SwitcherUrlProvider</argument>
                    <argument name="countryViewModel" xsi:type="object">Opengento\CountrySwitcher\ViewModel\SwitchCountry\More</argument>
                    <argument name="urlAction" xsi:type="url" path="stores/country/redirect"/>
                </arguments>
            </block>
        </referenceBlock>
```

Mobile view:
```xml
        <block name="store.settings.country" template="Opengento_CountrySwitcher::switch/country/forehead.phtml">
            <arguments>
                <argument name="id_modifier" xsi:type="string">nav</argument>
                <argument name="localized" xsi:type="object">Opengento\CountrySwitcher\ViewModel\Localized</argument>
                <argument name="switcherProvider" xsi:type="object">Opengento\CountrySwitcher\ViewModel\SwitcherUrlProvider</argument>
                <argument name="countryViewModel" xsi:type="object">Opengento\CountrySwitcher\ViewModel\SwitchCountry\Forehead</argument>
                <argument name="urlAction" xsi:type="url" path="stores/country/redirect"/>
            </arguments>
            <block class="Magento\Framework\View\Element\Template" name="store.settings.language.more" as="more" template="Opengento_CountrySwitcher::switch/country/more.phtml">
                <arguments>
                    <argument name="localized" xsi:type="object">Opengento\CountrySwitcher\ViewModel\Localized</argument>
                    <argument name="switcherProvider" xsi:type="object">Opengento\CountrySwitcher\ViewModel\SwitcherUrlProvider</argument>
                    <argument name="countryViewModel" xsi:type="object">Opengento\CountrySwitcher\ViewModel\SwitchCountry\More</argument>
                    <argument name="urlAction" xsi:type="url" path="stores/country/redirect"/>
                </arguments>
            </block>
        </referenceBlock>
```

**Comment by mondiedmond** [comment]
Thank you! Can i find a css file for the modal popup?

**Comment by thomas-kl1** [comment]
There is no css file shipped with the module, you need to edit the template to fit with your theme or create custom css.

**Comment by mondiedmond** [comment]
Hi! I have another question if you cand help me... 
I want to call this module in my header.phtml file.
Thank you!

**Comment by thomas-kl1** [comment]
Please could you describe a bit more what you want to achieve by "I want to call this module in my header.phtml file."?

Also a new version of the module will be released soon (improvements and fixtures) and it won't affect the frontend but you won't need anymore the following html attribute on your elements: data-role="country-switcher"

**Comment by mondiedmond** [comment]
I want to put the mobile view version in mobile menu but my mobile menu doesn't have an xml layout so i need to put the module in my mobile-header.phtml file with getChildHtml but doesn't work for me...

**Comment by thomas-kl1** [comment]
I don't know how your theme is configured, anyway the piece of code above works. Anyway I guess somewhere your template mobile-header.phtml is called in the layout xml or via a block. Beside that if you really don't have layout xml for your mobile menu, you can dynamically create the block in the phtml file and add the arguments with setData.
